unit JclDebugReaderTests;

// Smoke tests for the JCL debug-info provider (JclDebugReader). Exercises the
// address->location + procedure-name resolution path against TestTarget.jdbg
// (generated by build_jdbg.bat from TestTarget.map). TD32 is used as the ground
// truth oracle: a function RVA resolved by TD32 must resolve to the same
// function + source file (and line) through the JCL provider, which validates
// the ModuleCodeOffset ($1000) address convention end to end.
//
// Self-skips when TestTarget.jdbg is absent -- i.e. when JCL is not installed or
// the JCL_DEBUG define is off (CreateJclDebugProvider then returns nil).

interface

uses
  DUnitX.TestFramework, DebugInfoTypes;

type
  [TestFixture]
  TJclDebugReaderTests = class
  private
    function ExePath: string;
    // Creates the JCL provider for TestTarget.exe (shift 0). Calls Assert.Pass
    // and returns nil when no JCL data is present (build without JCL).
    function MakeProvider: IInterface;
    // A function RVA + its TD32 source location, used as the oracle.
    procedure Td32Oracle(out Rva: UInt64; out Loc: TSourceLocation; out FuncName: string);
  public
    [Test] procedure DataPresent_ForTestTarget;
    [Test] procedure Provider_ImplementsLineAndFuncInterfaces;
    [Test] procedure FuncName_KnownMethod_Resolves;
    [Test] procedure SourceLine_KnownMethod_MatchesTd32File;
    [Test] procedure FuncStart_WithinFunctionRange;
    [Test] procedure SortedRvas_NonEmpty;
    [Test] procedure SourceLineToRva_NotSupported;
    [Test] procedure NestedProcLinkage_NotProvided;
  end;

implementation

uses
  System.SysUtils, System.IOUtils,
  TD32FileReader, JclDebugReader, PeSymbolSupport;

const
  // A class method known to exist in TestTarget (also used by TD32ReaderTests).
  ORACLE_METHOD = 'TWidget.DoCalcInt64';

function TJclDebugReaderTests.ExePath: string;
begin
  Result := ExtractFilePath(ParamStr(0)) + '..\..\TestTarget\Win64\Debug\TestTarget.exe';
  if not TFile.Exists(Result) then
    Assert.Fail('TestTarget.exe not found at ' + Result + ' -- run build_target.bat first');
end;

function TJclDebugReaderTests.MakeProvider: IInterface;
begin
  Result := nil;
  if not CreateJclDebugProvider(ExePath, 0, ReadPEImageSize(ExePath), Result) then
    Assert.Pass('SKIP[no-jcl]: TestTarget.jdbg absent (JCL disabled or not generated)');
end;

procedure TJclDebugReaderTests.Td32Oracle(out Rva: UInt64; out Loc: TSourceLocation; out FuncName: string);
begin
  var R := TTD32FileReader.Create;
  try
    R.LoadFromFile(ExePath);
    Assert.IsTrue(R.NameToRva(ORACLE_METHOD, Rva),
      ORACLE_METHOD + ' must resolve via TD32 (oracle)');
    Assert.IsTrue(R.RvaToSourceLine(Rva, Loc),
      'TD32 must map the oracle RVA to a source line');
    Assert.IsTrue(R.RvaToFunctionName(Rva, FuncName));
  finally
    R.Free;
  end;
end;

procedure TJclDebugReaderTests.DataPresent_ForTestTarget;
begin
  var Linked: Boolean;
  var JdbgPath: string;
  if not JclDebugDataPresent(ExePath, Linked, JdbgPath) then
    Assert.Pass('SKIP[no-jcl]: no JCL data for TestTarget (JCL disabled or not generated)');
  Assert.IsTrue(Linked or (JdbgPath <> ''), 'either a linked section or a .jdbg path');
end;

procedure TJclDebugReaderTests.Provider_ImplementsLineAndFuncInterfaces;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var LineP: ISourceLineProvider;
  var FuncP: IFunctionNameProvider;
  Assert.IsTrue(Supports(Prov, ISourceLineProvider, LineP), 'must be an ISourceLineProvider');
  Assert.IsTrue(Supports(Prov, IFunctionNameProvider, FuncP), 'must be an IFunctionNameProvider');
end;

procedure TJclDebugReaderTests.FuncName_KnownMethod_Resolves;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var Rva: UInt64;
  var OracleLoc: TSourceLocation;
  var OracleName: string;
  Td32Oracle(Rva, OracleLoc, OracleName);

  var FuncP := Prov as IFunctionNameProvider;
  var Name: string;
  Assert.IsTrue(FuncP.RvaToFunctionName(Rva, Name),
    'JCL must name the oracle RVA');
  // JCL names are unit-qualified (e.g. TestTargetCore.TWidget.DoCalcInt64); the
  // TD32 oracle name is Class.Method. Require the JCL name to end with it.
  Assert.IsTrue(Name.EndsWith(ORACLE_METHOD, True),
    Format('JCL name "%s" must end with "%s"', [Name, ORACLE_METHOD]));
end;

procedure TJclDebugReaderTests.SourceLine_KnownMethod_MatchesTd32File;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var Rva: UInt64;
  var OracleLoc: TSourceLocation;
  var OracleName: string;
  Td32Oracle(Rva, OracleLoc, OracleName);

  var LineP := Prov as ISourceLineProvider;
  var Loc: TSourceLocation;
  Assert.IsTrue(LineP.RvaToSourceLine(Rva, Loc),
    'JCL must map the oracle RVA to a source line');
  Assert.IsTrue(Loc.Line > 0, 'JCL line must be positive');
  Assert.AreEqual(
    LowerCase(ExtractFileName(OracleLoc.SourceFile)),
    LowerCase(ExtractFileName(Loc.SourceFile)),
    'JCL and TD32 must agree on the source file for the same RVA');
  // The RVA is the method entry; both tables place its line record identically.
  Assert.AreEqual(OracleLoc.Line, Loc.Line,
    'JCL and TD32 must agree on the line at the function entry RVA');
end;

procedure TJclDebugReaderTests.FuncStart_WithinFunctionRange;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var Rva: UInt64;
  var OracleLoc: TSourceLocation;
  var OracleName: string;
  Td32Oracle(Rva, OracleLoc, OracleName);

  var FuncP := Prov as IFunctionNameProvider;
  var FuncRva: UInt64;
  Assert.IsTrue(FuncP.RvaToFunctionStart(Rva, FuncRva),
    'JCL must return the function start');
  Assert.IsTrue(FuncRva <= Rva, 'function start must be at or before the query RVA');
  // The start must itself name the same function.
  var Name: string;
  Assert.IsTrue(FuncP.RvaToFunctionName(FuncRva, Name));
  Assert.IsTrue(Name.EndsWith(ORACLE_METHOD, True),
    Format('start RVA name "%s" must end with "%s"', [Name, ORACLE_METHOD]));
end;

procedure TJclDebugReaderTests.SortedRvas_NonEmpty;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var LineP := Prov as ISourceLineProvider;
  Assert.IsTrue(Length(LineP.SortedRvas) > 0, 'JCL line table must surface RVAs');
end;

procedure TJclDebugReaderTests.SourceLineToRva_NotSupported;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var LineP := Prov as ISourceLineProvider;
  var Rva: UInt64;
  // JCL exposes no line->address lookup; the provider returns False by design.
  Assert.IsFalse(LineP.SourceLineToRva('TestTargetCore.pas', 1, Rva),
    'JCL line->address must be unsupported (TD32 owns BP binding)');
end;

procedure TJclDebugReaderTests.NestedProcLinkage_NotProvided;
begin
  var Prov := MakeProvider;
  if Prov = nil then Exit;
  var FuncP := Prov as IFunctionNameProvider;
  var Parent: string;
  // JCL does not preserve the mangled _ZZ/$pdata$ nested-proc publics, so the
  // enclosing-procedure linkage is intentionally unavailable (MAP owns it).
  Assert.IsFalse(FuncP.GetEnclosingProcedure('anything', Parent),
    'JCL must not claim nested-proc parent linkage');
end;

initialization
  TDUnitX.RegisterTestFixture(TJclDebugReaderTests);

end.
